name: CI

on: [push, pull_request]

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    
    - name: Download custom vcpkg and additional ports 
      shell: bash
      run: |
        git clone -b 2019.10 https://github.com/microsoft/vcpkg  C:/vcpkg-idjl
        C:/vcpkg-robotology/bootstrap-vcpkg.sh
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
    - name: Install vcpkg ports
      shell: bash
      run: |
        # TinyXML is not installed as a workaround for https://github.com/robotology/ycm/pull/296
        C:/vcpkg-robotology/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows eigen3 libxml2 eigen3 matio ipopt-binary protobuf boost-math boost-asio boost-thread ace
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/vcpkg-idjl/buildtrees 
        rm -rf C:/vcpkg-idjl/packages 
        rm -rf C:/vcpkg-idjl/downloads 
        
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-idjl
        path: C:/vcpkg-idjl
