name: CI

on: [push, pull_request]

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    
    - name: Check free space 
      shell: bash 
      run: |
        df -h
    
    - name: Download custom vcpkg and additional ports 
      shell: bash
      run: |
        mkdir C:/idjl
        git clone -b 2020.01 https://github.com/microsoft/vcpkg  C:/idjl/vcpkg
        C:/idjl/vcpkg/bootstrap-vcpkg.sh
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
    - name: Install vcpkg ports
      shell: bash
      run: |
        # Install dependencies for gazebo11 and related ignition dependencies (listed in https://bitbucket.org/osrf/gazebodistro/src/default/gazebo11.yaml)         
        C:/idjl/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows boost-asio boost-any boost-date-time boost-filesystem boost-format boost-interprocess boost-iostreams boost-program-options boost-property-tree boost-regex boost-smart-ptr boost-system boost-thread boost-variant boost-uuid bullet3 cppzmq curl dlfcn-win32 freeimage libyaml libzip jsoncpp ogre protobuf qt5-base qwt tbb tinyxml tinyxml2 urdfdom zeromq
        
        # Install direct dependencies of idjl-software, iDynTree and YARP
        C:/idjl/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows eigen3 libxml2 eigen3 matio ensenso-binary ipopt-binary protobuf asio ace pcl
        
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/idjl/vcpkg/buildtrees 
        rm -rf C:/idjl/vcpkg/packages 
        rm -rf C:/idjl/vcpkg/downloads 
        
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-idjl
        path: C:/idjl/vcpkg
