name: CI

on: 
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    
    - name: Check free space 
      shell: bash 
      run: |
        df -h

    - name: Download custom vcpkg and additional ports 
      shell: bash
      run: |
        mkdir C:/idjl
        git clone -b 2020.01 https://github.com/microsoft/vcpkg  C:/idjl/vcpkg
        C:/idjl/vcpkg/bootstrap-vcpkg.sh
        git clone https://github.com/robotology-dependencies/robotology-vcpkg-binary-ports C:/robotology-vcpkg-binary-ports
        
    # Workaround for https://github.com/actions/virtual-environments/issues/605
    - name: Remove faulty VS2019 16.5
      shell: powershell
      run: |
        Start-Sleep 5
        Remove-Item -Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610" -Force -Recurse

    - name: Install vcpkg ports
      shell: bash
      run: |
        # TinyXML is not installed as a workaround for https://github.com/robotology/ycm/pull/296
        C:/idjl/vcpkg/vcpkg.exe --overlay-ports=C:/robotology-vcpkg-binary-ports install --triplet x64-windows eigen3 libxml2 eigen3 matio ensenso-binary ipopt-binary protobuf asio ace pcl winpcap
        # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
        rm -rf C:/idjl/vcpkg/buildtrees 
        rm -rf C:/idjl/vcpkg/packages 
        rm -rf C:/idjl/vcpkg/downloads 
        
    - uses: actions/upload-artifact@master
      with:
        name: vcpkg-idjl
        path: C:/idjl/vcpkg
        
    - name: Prepare release file
      if: github.event_name == 'release'
      shell: cmd 
      run: |
        7z a vcpkg-idjl.zip C:\idjl
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./vcpkg-idjl.zip
          asset_name: vcpkg-idjl.zip
          asset_content_type: application/zip
